# Generated by Django 5.1 on 2026-04-26 00:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('color', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
