# Generated by Django 5.1 on 2026-04-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs", "0002_document_client"),
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentcategory",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doc_categories",
                to="tickets.client",
            ),
        ),
        migrations.AddField(
            model_name="documentcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="docs.documentcategory",
            ),
        ),
    ]
