# Generated by Django 5.1 on 2026-04-27

from django.db import migrations, models


def populate_display_name(apps, schema_editor):
    CustomUser = apps.get_model("accounts", "CustomUser")
    for user in CustomUser.objects.all().iterator():
        if user.display_name:
            continue
        user.display_name = user.full_name or user.username or user.email
        user.save(update_fields=["display_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="display_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(populate_display_name, migrations.RunPython.noop),
    ]
